model:
  batch_size: 8
  base_learning_rate: 0.0001
  ninp: 512
  nhead: 16
  nhid: 2048
  nlayers: 8
  dropout: 0.0
data:
  base_dir: /work/cseos2g/papapalpi/
  train_latents: data/videos/video_train_256x256_latent_diffusion.npy
  val_latents: data/videos/video_val_256x256_latent_diffusion.npy
  train_images: data/videos/video_train_256x256_latent_2.npy
  val_images: data/videos/video_val_256x256_latent_2.npy
