diffae:
  diffae_config: {diffae_config}
  checkpoint_file: {diffae_checkpoint}
model:
  gpus: 1
  nodes: 1
  batch_size: 128
  total_samples: {total_samples}
  latent_space: {latent_space}
data:
  train_dataset_length: {train_dataset_length}
  train: image_dataset_synthesis/train_images_64x64_latent.npy
  val: image_dataset_synthesis/val_images_64x64_latent.npy
  train_labels: image_dataset_synthesis/train_labels.npy
  val_labels: image_dataset_synthesis/val_labels.npy