diffae:
  diffae_config: {diffae_config}
  checkpoint_file: {diffae_checkpoint}
model:
  batch_size: 256
  total_samples: {total_samples}
data:
  train_dataset_length: {train_dataset_length}
  train: image_dataset_synthesis/train_images_64x64_latent.npy
  val: image_dataset_synthesis/val_images_64x64_latent.npy
  train_labels: image_dataset_synthesis/train_labels.npy
  val_labels: image_dataset_synthesis/val_labels.npy