diffae:
  diffae_config: {diffae_config}
  checkpoint_file: {diffae_checkpoint}
model:
  gpus: 1
  nodes: 1
  batch_size: 256
  total_samples: {total_samples}
  latent_space: {latent_space}
data:
  train_dataset_length: {train_dataset_length}
  train_images: {train_dataset_64x64}
  val_images: {val_dataset_64x64}
  train: {train_dataset_semantic}
  val: {val_dataset_semantic}
  train_labels: {train_dataset_labels}
  val_labels: {val_dataset_labels}